name: "Base build"

on: workflow_call
      
jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0
      DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
      TERM: xterm
      PROJECT_PATH: src/OpenAIPluginMiddleware.csproj
      TEST_PATH: tests
    outputs:
      version: ${{ steps.set_proj_version.outputs.PKG_VERSION }}
      relnotes: ${{ steps.set_proj_version.outputs.RELNOTES }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
      
    - name: 🧰 Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    # NOTE: this echo hack is due to https://github.com/dotnet/sdk/issues/10310
    - name: 🧰 Install NBGV
      run: dotnet tool install -g nbgv | echo "already installed"

    - name: ☀️ Set Version
      run: nbgv cloud

    - name: ♻️ Restore
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 🏗️ Build
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

    - name: 🧪 Test
      run: dotnet test ${{ env.TEST_PATH }} --logger "GitHubActions;summary.includePassedTests=true;summary.includeSkippedTests=true"

    - name: 💼 Pack
      run: dotnet pack ${{ env.PROJECT_PATH }} --configuration Release -o finalpackage --no-build

    - name: ⬆️ Publish artifact
      uses: actions/upload-artifact@v3
      with:
        name: nupkg
        path: finalpackage

    - name: Get version
      id: set_proj_version
      shell: pwsh
      run: |
        [xml]$nuspec = Get-Content ${{ env.PROJECT_PATH }}
        $nbgv = nbgv get-version -f json | ConvertFrom-Json
        $version=$nbgv.NuGetPackageVersion
        $relnotes=$nuspec.project.propertygroup.packagereleasenotes
        Add-Content -Path $env:GITHUB_OUTPUT -Value "PKG_VERSION=$version"
        Add-Content -Path $env:GITHUB_OUTPUT -Value "RELNOTES=$relnotes"

    - name: 🏷️ Tag and Release
      id: tag_release
      uses: softprops/action-gh-release@v0.1.15
      with:
          body: ${{ steps.set_proj_version.outputs.relnotes }}
          tag_name: ${{ steps.set_proj_version.outputs.pkg_version }}
          generate_release_notes: true
          files: |
            **/*.nupkg