name: "Build and publish"

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      
jobs:
  build:
    name: Build
    uses: ./.github/workflows/_build.yaml

  publish:
    needs: build
    name: Publish
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://www.nuget.org/packages/TimHeuer.OpenAIPluginMiddleware
    permissions:
      contents: write
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0
      DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
      TERM: xterm
    steps:
      - name: ⬇️ Download Package artifact
        uses: actions/download-artifact@v3
        with:
          name: nupkg

      - name: 🧰 Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: 🔐 Get certificate
        id: cert_file
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'certfile.pfx'
          encodedString: ${{ secrets.SIGNING_CERT }}
      
      - name: ✍️ Sign NuGet Package
        run: dotnet nuget sign **/*.nupkg --certificate-path ${{ steps.cert_file.outputs.filePath }} --certificate-password ${{ secrets.CERT_PWD }} --timestamper http://timestamp.digicert.com
      
      - name: 👇 Push to NuGet
        run: dotnet nuget push **/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate

      - name: 🏷️ Tag and Release
        id: tag_release
        uses: softprops/action-gh-release@v0.1.15
        with:
          body: ${{ needs.build.outputs.relnotes }}
          tag_name: ${{ needs.build.outputs.version }}
          generate_release_notes: true
          files: |
            **/*.nupkg

      - name: ⬆️ Publish signed artifact
        uses: actions/upload-artifact@v3
        with:
          name: signednupkg
          path: .